### ISSUE TITLE
whereIn bug

### ISSUE THREAD

**Issue by xtiktok** [alexSivka/sivka-db#1]
/**
     * @param {string} column - column name
     * @param {Array} values - array of values
     * @returns this
     */
    whereIn(column, values){
        console.log(this.wrapField(column) + " IN (" + values.join(',') + ")")
        return this.where(this.wrapField(column) + " IN ('" + values.join(',') + "')");
    }

++++++++++++++++++++++++++++++++
在用 whereIn(name,['我是中国人']) 时会有bug，  数组里面是字符串的时候会有bug

**Comment by alexSivka** [comment]
Hello, thanks, will fix this in nearest release

**Comment by alexSivka** [comment]
fixed
